export const GET_TRENDING_COINS = "GET_TRENDING_COINS";
export const GET_ALL_COINS = "GET_ALL_COINS";
export const GET_HISTORY_CHART = "GET_HISTORY_CHART";
export const GET_COIN_BY_NAME = "GET_COIN_BY_NAME";
